name: Check PR Description

on:
  pull_request:
    types: [opened, edited]
    branches:
      - main

jobs:
  check-description:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Description
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            if (!pr.body) {
              const message = 'Please fill in an adequate commit message; please note that PR commit messages might get published in release notes as well.';
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: message
              });

              // Fail the job
              core.setFailed('PR description is missing.');
            }
