name: PR Description Check

on:
  pull_request:
    types: [opened, edited, reopened]
    branches: [main]

jobs:
  check-description:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Description
        uses: actions/github-script@v6
        with:
          script: |
            if (!github.context.payload.pull_request.body || github.context.payload.pull_request.body.trim().length === 0) {
              const comment = 'Please provide a description.';
              await github.rest.issues.createComment({
                owner: github.context.repo.owner,
                repo: github.context.repo.repo,
                issue_number: github.context.payload.pull_request.number,
                body: comment
              });
              await github.rest.pulls.update({
                owner: github.context.repo.owner,
                repo: github.context.repo.repo,
                pull_number: github.context.payload.pull_request.number,
                state: 'closed'
              });
            }
