name: PR Description Check

on:
  pull_request:
    types: [opened, edited, reopened]
    branches: [main]

jobs:
  check-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: gh auth setup-git

      - name: Check PR Description
        run: |
          pr_number=${{ github.event.pull_request.number }}
          pr_body=$(gh pr view $pr_number --json body -q '.body')

          if [ -z "$pr_body" ] || [ "$pr_body" == "null" ] || [ -z "${pr_body// }" ]; then
            gh pr comment $pr_number --body "Please provide a description."
            gh pr close $pr_number
          fi
