name: PR Description Check

on:
  pull_request:
    types: [opened, edited, reopened]
    branches: [develop]

jobs:
  check-description:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Description
        uses: actions/github-script@v6
        with:
          script: |
            const pr = github.context.payload.pull_request;
            if (!pr.body || pr.body.trim().length === 0) {
              const comment = 'Please provide a description.';
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: comment
              });
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                state: 'closed'
              });
            }
