name: PR Description Check

on:
  pull_request:
    types: [opened, edited, reopened]
    branches: [main]

jobs:
  check-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Check PR Description
        run: |
          pr_number=${{ github.event.pull_request.number }}
          pr_body=$(gh pr view $pr_number --json body -q '.body')
          message="${{ secrets.PR_DESCRIPTION_MESSAGE }}"

          if [ -z "$pr_body" ] || [ "$pr_body" == "null" ] || [ -z "${pr_body// }" ]; then
            gh pr comment $pr_number --body "$message"
            gh pr close $pr_number
          fi
