name: PR Description Validation and Closure

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
    branches: 
      - main  # Update this to 'develop' after testing

jobs:
  check-description:
    runs-on: auto-u22-base
    env:
      GH_HOST: git.hub.vwgroup.com
      GH_ENTERPRISE_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: echo ${{ env.GH_ENTERPRISE_TOKEN }} | gh auth login --with-token

      - name: Check PR Description
        run: |
          set -e
          pr_number=${{ github.event.pull_request.number }}
          echo "Fetching PR number: $pr_number"

          # Debug output for PR number and variable
          echo "PR number: $pr_number"
          echo "PR Description Message: ${{ vars.PR_DESCRIPTION_MESSAGE }}"

          pr_body=$(gh pr view $pr_number --json body -q '.body')
          echo "PR Body: $pr_body"

          pr_body_trimmed=$(echo "$pr_body" | xargs)

          if [ -z "$pr_body_trimmed" ]; then
            echo "PR body is empty or null. Commenting and closing PR."

            # Use the repository variable here
            gh pr comment $pr_number --body "${{ vars.PR_DESCRIPTION_MESSAGE }}" || { echo "Failed to comment on PR"; exit 1; }
            gh pr close $pr_number || { echo "Failed to close PR"; exit 1; }
          else
            echo "PR body is sufficient."
          fi
