name: Fetch Repo Data and Generate HTML

on:
  push:
  workflow_dispatch:

jobs:
  fetch-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Fetch Script
        env:
            TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
            REPO_USER_NAME: ${{ github.repository_owner }}
            REPO_NAME: ${{ github.event.repository.name }}
        run: node src/fetchRepoData.mjs

      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: repo-data-report.html
