name: Fetch Pull Requests

on:
  push:  
  workflow_dispatch:
jobs:
  fetch-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Fetch open pull requests
        id: fetch-open-prs
        run: |
          gh pr list --repo <owner>/<repo> --state open --json number,title > open-prs.json

      - name: Fetch closed pull requests
        id: fetch-closed-prs
        run: |
          gh pr list --repo <owner>/<repo> --state closed --json number,title > closed-prs.json

      - name: Output open pull requests
        run: |
          echo "Open Pull Requests:"
          cat open-prs.json

      - name: Output closed pull requests
        run: |
          echo "Closed Pull Requests:"
          cat closed-prs.json